version: "3.3"
services:
      
  redis:
    image: redis
    hostname: redis
    networks:
      - hpndev
    ports:
      - 6379:6379

  exec:
    build: ./docker/dev/
    volumes:
      - './:/home'
    command: ["bash", "-c", "${FILE}"]
    ipc: host
    shm_size: 4GB
    depends_on:
      - redis
    networks:
      - hpndev

  shell:
    build: ./docker/dev/
    volumes:
      - './:/home'
    command: ["bash", "-c", "${FILE}"]
    ipc: host
    networks:
      - hpndev

  tests:
    build: ./docker/dev/
    volumes:
      - './:/home'
    command: ["node", "./tests/unit"]
    depends_on:
      - redis
    networks:
      - hpndev

  

networks:
  hpndev:

